sudo: required
language: c

os:
    - linux
    - linux-ppc64le

env:
    global:
        - PACKAGE=sbd
        - BUILD_OS_TYPE=fedora BUILD_OS_DIST= BUILD_OS_VERSION=29

matrix:
    exclude:
        - os:  linux
        - os:  linux-ppc64le

    include:
        - os:  linux
          env: OS_ARCH=x86_64 OS_TYPE=centos OS_MOCK=epel OS_DIST=centos OS_VERSION=7
        - os:  linux
          env: OS_ARCH=x86_64 OS_TYPE=centos OS_MOCK=epel OS_DIST=centos OS_VERSION=6
        - os:  linux
          env: OS_ARCH=x86_64 OS_TYPE=fedora OS_MOCK=fedora OS_DIST= OS_VERSION=28
        - os:  linux
          env: OS_ARCH=x86_64 OS_TYPE=fedora OS_MOCK=fedora OS_DIST= OS_VERSION=29
        - os:  linux-ppc64le
          env: OS_ARCH=ppc64le OS_TYPE=fedora OS_MOCK=fedora OS_DIST= OS_VERSION=29

services:
  - docker

install: true

script:
  - make -f Makefile.am srpm PACKAGE=${PACKAGE}
  - docker pull ${BUILD_OS_TYPE}:${BUILD_OS_DIST}${BUILD_OS_VERSION}
  - docker run --privileged -v ${PWD}:/rpms ${BUILD_OS_TYPE}:${BUILD_OS_DIST}${BUILD_OS_VERSION} /bin/bash -c "dnf install -y mock dnf-utils && mock --no-clean -r ${OS_MOCK}-${OS_VERSION}-${OS_ARCH} --resultdir=/rpms --disable-plugin=yum_cache --disable-plugin=selinux --no-bootstrap-chroot --old-chroot /rpms/sbd*.src.rpm"
  - ls ${PWD}/${PACKAGE}*.${OS_ARCH}.rpm
  - docker pull ${OS_TYPE}:${OS_DIST}${OS_VERSION}
  - docker run --privileged -v ${PWD}:/rpms -v ${PWD}/tests:/tests ${OS_TYPE}:${OS_DIST}${OS_VERSION} /bin/bash -c "yum install -y device-mapper /rpms/${PACKAGE}*.${OS_ARCH}.rpm && /tests/regressions.sh && touch /rpms/regressions.sh.SUCCESS"
  - ls ${PWD}/regressions.sh.SUCCESS

addons:
  apt:
    packages:
        - rpm


