sudo: required
language: c

env:
  global:
    - DOCKER_BUILD_IMAGE=alectolytic/rpmbuilder
    - OS_ARCH=x86_64
    - PACKAGE=sbd
  matrix:
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=7
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=6

services:
  - docker

install: true

script:
  - make -f Makefile.am spec export PACKAGE=${PACKAGE}
  - docker run -v ${PWD}:/sources -v ${PWD}:/output ${DOCKER_BUILD_IMAGE}:${OS_TYPE}-${OS_VERSION}
  - ls ${PWD}/sbd*.${OS_ARCH}.rpm
